### ISSUE TITLE
mouse tracking not working in vue.js

### ISSUE THREAD

**Issue by Msiavashi** [MetaMask/logo#17]
Hello
thanks for your beautiful work.

i have tried using this in my vue.js application. i've done the following things when my template mounted:

here is my div:

`                                    <div ref="metamask"></div>`

and here is how i initialize and attach the logo to this div:

 ```
   mounted: function(){

        // initializing and appending the MetaMask Logo to its Div
        let metaMaskViewer = ModelViewer({
            pxNotRatio: true,
            width: 500,
            height: 400,
            follwoMouse: false,
            slowDrift: false
        });
        this.$refs.metamask.appendChild(metaMaskViewer.container);
        metaMaskViewer.lookAt({
            x:100,
            y:100
        });
        // enable mouse follow
        metaMaskViewer.setFollowMouse(true)

        // deallocate nicely
        metaMaskViewer.stopAnimation()
    }
```

it displays the svg very nicely but the problem is it does not follow the mouse anyway, it just looks straight in my eyes. not errors to track the problem.
any idea to solve this ?

Thanks in advance

**Comment by Jandoria** [comment]
I think I'm a bit late but you wrote follwoMouse instead of followMouse.
Plus I don't think you should stop the animation.

**Comment by Msiavashi** [comment]
Ooooh... I spent days working on it :)))) thanks mate. it works now but not without         `metaMaskViewer.stopAnimation()`
